### ISSUE TITLE
Feature Request : Plugin is short of features like setting initialnumber and getting current accoun

### ISSUE THREAD

**Issue by uzumakinaruto123** [gurisko/cordova-plugin-accountkit#12]
Plugin is short of features like setting initialnumber and getting current account.

 I manually added `setting initial number and getting account`  to the plugin.  But , I can't make a PR (actually I don't know how to) because I did it only for android. I don't know anything of iOS.  

It would be great if you could do it on your end, and for ios.

Thanks.

**Comment by gurisko** [comment]
Hello @uzumakinaruto123. I will be adding `getAccount()` method soon. Is there any chance of you publishing your android implementation into your fork? I can cherry pick it into this repo.
I haven't thought about initial number just yet, but it seems easy to be done. I will have a look.

**Comment by uzumakinaruto123** [comment]
@gurisko  Yes its easy :D I will update here once I publish to fork :)

**Comment by uzumakinaruto123** [comment]
@gurisko  [https://github.com/uzumakinaruto123/cordova-plugin-accountkit/tree/addfeature](https://github.com/uzumakinaruto123/cordova-plugin-accountkit/tree/addfeature)  here.   :)  

Only one thing short here is , the Country code for initial parameter is static and not dynamic. I mean I have set it to mine.

**Comment by gurisko** [comment]
Thank you @uzumakinaruto123. I had a look at your contribution and I tried to cherry pick. However I ended up with quite a big refactoring and it couldn't work together eventually. I hope you will find the changes satisfying!

This can be closed.

**Comment by uzumakinaruto123** [comment]
Great ! :) will update
