### ISSUE TITLE
lastRefresh / refreshInterval

### ISSUE THREAD

**Issue by 1N50MN14** [gurisko/cordova-plugin-accountkit#16]
Hey! Thanks for the awesome plugin! ;)

Question, `lastRefresh` and `refreshInterval` are those in seconds or milliseconds and are they consistent in both iOS and Android (the formatting)?

Thank you ;)

**Comment by gurisko** [comment]
Hello @1N50MN14 ! Thank you for trying the plugin and for your feedback. It seems that we should include these information into README.

To answer your question:
`lastRefresh` - returns milliseconds
`refreshInterval` -  returns seconds

They are consistent on both platforms (small difference is lastRefresh which returns double for iOS and int for android).

**Comment by 1N50MN14** [comment]
Thanks for the clarification @gurisko - closing issue - PS +1 for #2 ;)

**Comment by 1N50MN14** [comment]
closing
