### ISSUE TITLE
iOS linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by 1N50MN14** [gurisko/cordova-plugin-accountkit#17]
The build fails when using along with phonegap-plugin-push, xcode throws build error `clang: error: linker command failed with exit code 1 (use -v to see invocation)` :( Any ideas how to resolve this? here's the full log:
>Ld /Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Products/Debug-iphoneos/Twirm.app/Twirm normal arm64
    cd /Users/ayman/twirm/webapp/src/cordova/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Products/Debug-iphoneos -L/Users/ayman/twirm/webapp/src/cordova/platforms/ios/Pods/GGLInstanceID/Libraries -L/Users/ayman/twirm/webapp/src/cordova/platforms/ios/Pods/GoogleCloudMessaging/Libraries -F/Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Products/Debug-iphoneos -F/Users/ayman/twirm/webapp/src/cordova/platforms/ios/Pods/GoogleIPhoneUtilities/Frameworks -F/Users/ayman/twirm/webapp/src/cordova/platforms/ios/Pods/GoogleInterchangeUtilities/Frameworks -F/Users/ayman/twirm/webapp/src/cordova/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks -F/Users/ayman/twirm/webapp/src/cordova/platforms/ios/Pods/GoogleUtilities/Frameworks -FTwirm/Plugins/cordova-plugin-accountkit -filelist /Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Intermediates/Twirm.build/Debug-iphoneos/Twirm.build/Objects-normal/arm64/Twirm.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Intermediates/Twirm.build/Debug-iphoneos/Twirm.build/Objects-normal/arm64/Twirm_lto.o -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGGLInstanceIDLib -lGcmLib -lsqlite3 -lz -framework AddressBook -framework CoreGraphics -framework GoogleIPhoneUtilities -framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities -framework GoogleUtilities -framework SystemConfiguration /Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Products/Debug-iphoneos/libCordova.a -framework AccountKit -weak_framework ImageIO -framework CoreLocation -framework AVFoundation -weak_framework AudioToolbox -weak_framework SystemConfiguration -framework CoreTelephony -weak_framework WebKit -framework CoreBluetooth -framework CoreMotion -framework Photos -framework AddressBook -framework EventKit -framework Contacts -framework UserNotifications -lsqlite3 -lz -lPods-Twirm -Xlinker -dependency_info -Xlinker /Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Intermediates/Twirm.build/Debug-iphoneos/Twirm.build/Objects-normal/arm64/Twirm_dependency_info.dat -o /Users/ayman/Library/Developer/Xcode/DerivedData/Twirm-gfilgmeucxxdicftqukpxoqdpnqu/Build/Products/Debug-iphoneos/Twirm.app/Twirm
> ld: library not found for -lPods-Twirm
>clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gurisko** [comment]
Hello @1N50MN14 . This doesn't seem like an issue with our plugin. Are you aware that push plugin is using [CocoaPods](https://cocoapods.org/) now?
> PushPlugin uses Cocoa Pods now, once it is installed you can not run your regular yourProjectName.xcodeproj file you must open a new file that was creating after you installed PushPlugin called yourProjectName.xcworkspace.

**Comment by 1N50MN14** [comment]
Oh I noticed the change regarding CocoaPods but didn't notice the `.xcworkspace` thingie... this did it.. wow thank @gurisko !
