### ISSUE TITLE
AccountKitPlugin is not defined

### ISSUE THREAD

**Issue by NikicaAsanin** [gurisko/cordova-plugin-accountkit#18]
I put function on button to register with phone number. But I am getting message like : AccountKitPlugin is not defined ? Help :)

**Comment by NikicaAsanin** [comment]
My function : 
```
 $scope.loginWithSMS = function($scope) {

        window.AccountKitPlugin.loginWithPhoneNumber( {
        initialPhoneNumber: ["381", "604833322"]
          },
          function (response){
            response.status = "Uspesno";
            alert("Uspesno");
        },
        function(response){
          response.status = "Greska";
          alert("Greska");
        });
}
```

> SystemWebChromeClient: file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 26799 : TypeError: Cannot call method 'loginWithPhoneNumber' of undefined
>                              at Scope.$scope.loginWithSMS (file:///android_asset/www/js/controllers.js:24:33)
>                              at fn (eval at <anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:1:0), <anonymous>:4:227)
>                              at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:65429:9
>                              at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30400:28)
>                              at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30500:25)
>                              at HTMLButtonElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:65428:13)
>                              at defaultHandlerWrapper (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:16792:11)
>                              at HTMLButtonElement.eventHandler (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:16780:9)
>                              at triggerMouseEvent (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2953:7)
>                              at tapClick (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2942:3)

**Comment by gurisko** [comment]
Which version are you using

**Comment by gurisko** [comment]
Please update to the latest - v1.2.0 since you are passing option parameter which was not in v1.1.4.

However this doesn't seem like a problem with the plugin. Please refer to any tutorial on how to include a plugin in Ionic1 without using ngCordova.
