### ISSUE TITLE
error loginWithPhoneNumber

### ISSUE THREAD

**Issue by phonenatural** [gurisko/cordova-plugin-accountkit#24]
hello,
i have problem with recieve the sms.  The SMS just have ???????????????????????????????????????  

I do not have errors in logcat...

help me.

**Comment by gurisko** [comment]
Could you be more specific about the device, operating system? Snippet and screenshot might help as well.

**Comment by phonenatural** [comment]
ok,  

Device: Samsung galaxy grand neo plus.

O.S : Android 4.4.4

The code is:
![cod](https://cloud.githubusercontent.com/assets/23510759/24958626/55496ba0-1f66-11e7-89df-07fa2f145400.png)

LogCat:  nothing

Img app:
1) this is facebook number in the app:
![screenshot_2017-04-12-10-02-13](https://cloud.githubusercontent.com/assets/23510759/24959094/073fbed0-1f68-11e7-8c80-c76c7afc15db.png)

2) success and wait sms with code
![screenshot_2017-04-12-10-02-31](https://cloud.githubusercontent.com/assets/23510759/24959148/33033dc6-1f68-11e7-88bd-49ef85e4e1c8.png)

3) SMS with code , but just have "?"
![screenshot_2017-04-12-10-02-40](https://cloud.githubusercontent.com/assets/23510759/24959182/4cb81552-1f68-11e7-9f22-973682015451.png)

4)  second later i recieve other sms
![screenshot_2017-04-12-10-05-43](https://cloud.githubusercontent.com/assets/23510759/24959226/761ea3c0-1f68-11e7-8450-fc2928448d87.png)

**Comment by gurisko** [comment]
Oh wow. This is the first time I actually see this happening. Explanation can be found [here](https://www.accountkit.com/faq/#11):

> Account Kit uses different kinds of SMS code to make sure you have the best experience. In some cases, however, your mobile carrier or network may not support this code. If you have a Facebook account and have your phone number listed on Facebook, you can choose to receive a notification on Facebook to complete the login process.

This is AccountKit issue and not the issue of this plugin.

**Comment by phonenatural** [comment]
ok, thank and keep it open please.
Can happen to another

**Comment by gurisko** [comment]
I don't think we should keep this open only because this can happen to everyone.

What we can do:
* Add this as a **known issue** into README file to make this more visible.
* Discuss whether we can catch this issue on the plugin side and throw a specific error

**Comment by phonenatural** [comment]
OK,  you can close the issue, I verify problem and effectively as it says facebook:  is a problem of telefony companies.
I checked and some companies have the problem and other no.

bye...
