### ISSUE TITLE
iOS strings are missing

### ISSUE THREAD

**Issue by gurisko** [gurisko/cordova-plugin-accountkit#5]
AccountKitStrings.bundle is not linked with the plugin:
<img width="301" alt="screen shot 2016-10-22 at 4 48 06 pm" src="https://cloud.githubusercontent.com/assets/495549/19620183/9b7047fa-9877-11e6-8ca6-11198daf58c3.png">

**Comment by kingkarki** [comment]
its 2018 and i m still having the same issue  https://ibb.co/hsmn0y

**Comment by gurisko** [comment]
@kingkarki Feel free to make your own pull request.
