### ISSUE TITLE
Documentation update needed and on submitting number returns 'something went wrong' message.

### ISSUE THREAD

**Issue by uzumakinaruto123** [gurisko/cordova-plugin-accountkit#9]
1. Using plugin in ionic 2 , plugin does not work with **'accountKitPlugin'** . After wasting a lot of time and checking the source discovered that plugin exports **'AccountKitPlugin'**. It worked once I changed accountKitPlugin to AccountKitPlugin.

2. On submitting phone number , it says `'something went wrong'` every time as in the screenshot 

<img src="https://cloud.githubusercontent.com/assets/15323421/21177268/62292a4e-c210-11e6-89d1-aac48f6e2e3f.png" alt="alt text" width="180" height="320">

It didn't ask for permissions so I manually changed permission from settings , and still the result was same.

Thanks or the plugin :)

**Comment by denyo** [comment]
About 1.) that's what my PR was for: https://github.com/gurisko/cordova-plugin-accountkit/pull/8

**Comment by uzumakinaruto123** [comment]
Figured out the issue , It need one extra step for this to work.

We need to enable `Enable client access token flow` from facebook developer console , otherwise this does not work. this should go in docs too

**Comment by gurisko** [comment]
First of all, thank you very much @uzumakinaruto123  for submitting the issue.

Since it seems that your 1st comment is more common than I previously thought, I cherry picked @denyo's pull request #8. (Thank you @denyo!)

About the second point - I don't recall setting that up anymore. Could you please write a sentence or two about it into this issue or into a pull request? Thanks

**Comment by Nicolaidavies** [comment]
@gurisko, I believe @uzumakinaruto123 's second issue is that the plugin is currently configured to only work with access tokens. AccountKit also allows you to authorise and receive a code back.

The solution seems to be to change line 94 of `AccountKitPlugin.java` from `AccountKitActivity.ResponseType.TOKEN` to `AccountKitActivity.ResponseType.CODE`for people needing to authorise using a code. see [https://developers.facebook.com/docs/accountkit/android#smslogin](https://developers.facebook.com/docs/accountkit/android#smslogin)

That would solve the problem for people not wanting to enable client access token flow. A better solution would be to allow users to choose if they want use access tokens or codes. So passing an object with options when logging in is probably the easiest.

My Java is not very good, I might try to submit a PR later on. 

Let me know if anything is unclear.

**Comment by gurisko** [comment]
@Nicolaidavies I like the solution where we give users the choice in between token and code. PR will be very appreciated! Thank you

**Comment by uzumakinaruto123** [comment]
@gurisko @Nicolaidavies  Sorry for late reply. But , regarding 2. I had to do it to get it working. Now I know why.  :)

**Comment by gurisko** [comment]
Let's close this issue after we update README with additional installation step.

**Comment by gurisko** [comment]
This was resolved in 86503be8b7cd69580cb3c2ce5f797000bd3a6f12
